### ISSUE TITLE
Imported libraries

### ISSUE THREAD

**Issue by AlexandrLysenko** [f1ypantera/Main-code#7]
https://github.com/f1ypantera/Main-code/blob/8ffb8b9dfbdaa7df4fec37182c41c1d039301fa8/Country.cs#L6
https://github.com/f1ypantera/Main-code/blob/8ffb8b9dfbdaa7df4fec37182c41c1d039301fa8/Country.cs#L4
Are you using this libraries?

**Comment by f1ypantera** [comment]
Yes
